version: "3"
   
services:
  db:
    image: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USR}
      - POSTGRES_PASSWORD=${POSTGRES_KEY}
    ports:
      - '5432:5432'
  app:
    build: .
    working_dir: /app/currencyAppApi
    command: 
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file: .env
    volumes:
      - ./app:/app
      - ./data/dev-static-data:/vol/web
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  dbdata: