version: "3.9"
   
services:

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${}
      - POSTGRES_USER=${POSTGRES_USR}
      - POSTGRES_PASSWORD=${POSTGRES_KEY}
    ports:
      - '5432:5432'

  app:
    build: .
    command: 
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    ports:
      - "8000:8000"
    depends_on:
      - db