# Generated by Django 4.1 on 2022-08-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('symbol', models.CharField(max_length=10)),
                ('base', models.CharField(default='USD', max_length=10)),
                ('bs_sym_rate', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('likes_total', models.IntegerField(default=0)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
